"""HarmonyOS SDK Repository Rule

自动下载 HarmonyOS 命令行工具链，无需手动安装 DevEco Studio。
支持 macOS 和 Linux。
"""

# hos-sdk 版本和下载地址
_HOS_SDK_VERSION = "2.0.0.2"
_HOS_SDK_TAG = "v2.0.2"

_HOS_SDK_URLS = {
    "mac": "https://github.com/harmonyos-dev/hos-sdk/releases/download/{tag}/commandline-tools-mac-{version}.zip",
    "linux": "https://github.com/harmonyos-dev/hos-sdk/releases/download/{tag}/commandline-tools-linux-{version}.zip",
}

# SHA256 checksums
_HOS_SDK_SHA256 = {
    "mac": "60247ea290a26fedba60c920394051687eabe53c36f70e049a807f05990b5c3e",
    "linux": "897efe0e4df015e44869f9322026fbd80c365a1d67387031168ab53c6eb6d0d4",
}

def _detect_os(repository_ctx):
    """检测操作系统类型"""
    os_name = repository_ctx.os.name.lower()
    if "mac" in os_name or "darwin" in os_name:
        return "mac"
    elif "linux" in os_name:
        return "linux"
    else:
        fail("Unsupported OS: " + os_name + ". HarmonyOS SDK only supports macOS and Linux.")

def _hos_sdk_repository_impl(repository_ctx):
    """下载并配置 HarmonyOS SDK"""
    
    os_type = _detect_os(repository_ctx)
    version = repository_ctx.attr.version or _HOS_SDK_VERSION
    tag = repository_ctx.attr.tag or _HOS_SDK_TAG
    
    # 构建下载 URL
    url = _HOS_SDK_URLS[os_type].format(tag = tag, version = version)
    sha256 = _HOS_SDK_SHA256.get(os_type, "")
    
    # 如果用户提供了自定义 URL，使用自定义 URL
    if repository_ctx.attr.url:
        url = repository_ctx.attr.url
        sha256 = repository_ctx.attr.sha256 or ""
    
    repository_ctx.report_progress("Downloading HarmonyOS SDK for %s..." % os_type)
    
    # 下载 SDK
    download_result = repository_ctx.download_and_extract(
        url = url,
        sha256 = sha256 if sha256 else None,
        stripPrefix = repository_ctx.attr.strip_prefix or "",
    )
    
    # 安装额外的 SDK 组件（如果需要）
    if repository_ctx.attr.install_components:
        _install_sdk_components(repository_ctx, repository_ctx.attr.install_components)
    
    # 生成 BUILD.bazel 文件
    repository_ctx.file("BUILD.bazel", _generate_build_file(repository_ctx, os_type))
    
    # 生成工具链配置文件
    repository_ctx.file("toolchain.bzl", _generate_toolchain_bzl(repository_ctx))

def _install_sdk_components(repository_ctx, components):
    """使用 sdkmgr 安装 SDK 组件"""
    sdkmgr = repository_ctx.path("command-line-tools/sdkmgr/bin/sdkmgr")
    
    if not sdkmgr.exists:
        # 尝试其他可能的路径
        sdkmgr = repository_ctx.path("sdkmgr/bin/sdkmgr")
    
    if not sdkmgr.exists:
        repository_ctx.report_progress("Warning: sdkmgr not found, skipping component installation")
        return
    
    for component in components:
        repository_ctx.report_progress("Installing SDK component: %s" % component)
        result = repository_ctx.execute(
            [str(sdkmgr), "install", component, "--accept-license"],
            timeout = 600,  # 10 分钟超时
        )
        if result.return_code != 0:
            repository_ctx.report_progress("Warning: Failed to install %s: %s" % (component, result.stderr))

def _generate_build_file(repository_ctx, os_type):
    """生成 BUILD.bazel 文件"""
    return '''# Auto-generated by hos_sdk_repository rule
# HarmonyOS SDK for {os_type}

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sdk",
    srcs = glob(["**/*"]),
)

# sdkmgr 在 bin/sdkmgr 或 sdkmanager/bin/sdkmgr
filegroup(
    name = "sdkmgr",
    srcs = glob(["bin/sdkmgr", "sdkmanager/bin/sdkmgr"], allow_empty = True),
)

# ohpm 在 ohpm/bin/ohpm
filegroup(
    name = "ohpm",
    srcs = glob(["ohpm/bin/ohpm"], allow_empty = True),
)

# hvigorw 通常需要通过 npm 安装，这里预留
filegroup(
    name = "hvigorw",
    srcs = glob(["hvigor/bin/hvigorw"], allow_empty = True),
)

# 导出所有文件
exports_files(glob(["**/*"], allow_empty = True))
'''.format(os_type = os_type)

def _generate_toolchain_bzl(repository_ctx):
    """生成工具链配置文件"""
    return '''# Auto-generated toolchain paths
# 使用方法: load("@hos_sdk//:toolchain.bzl", "HOS_SDK_PATH")

# HOS SDK 路径（相对于 Bazel workspace）
# 在运行时可通过 $(location @hos_sdk//:sdk) 获取
HOS_SDK_PATH = "external/hos_sdk"
'''

hos_sdk_repository = repository_rule(
    implementation = _hos_sdk_repository_impl,
    attrs = {
        "version": attr.string(
            doc = "HOS SDK 版本号",
            default = _HOS_SDK_VERSION,
        ),
        "tag": attr.string(
            doc = "GitHub release tag",
            default = _HOS_SDK_TAG,
        ),
        "url": attr.string(
            doc = "自定义下载 URL（覆盖默认）",
        ),
        "sha256": attr.string(
            doc = "下载文件的 SHA256 校验和",
        ),
        "strip_prefix": attr.string(
            doc = "解压后去除的路径前缀",
            default = "command-line-tools",
        ),
        "install_components": attr.string_list(
            doc = "要安装的 SDK 组件列表",
            default = [],
        ),
    },
    doc = """下载 HarmonyOS SDK 命令行工具

用于 CI 和本地构建，无需安装 DevEco Studio。

示例:
    # MODULE.bazel
    hos_sdk = use_extension("//bazel/harmonyos:extensions.bzl", "hos_sdk")
    hos_sdk.sdk()
    use_repo(hos_sdk, "hos_sdk")

或者:
    # WORKSPACE
    load("//bazel/harmonyos:repository.bzl", "hos_sdk_repository")
    hos_sdk_repository(name = "hos_sdk")
""",
)

def _hos_sdk_extension_impl(module_ctx):
    """Bzlmod 扩展实现"""
    for mod in module_ctx.modules:
        for sdk in mod.tags.sdk:
            hos_sdk_repository(
                name = sdk.name or "hos_sdk",
                version = sdk.version,
                tag = sdk.tag,
                url = sdk.url,
                sha256 = sdk.sha256,
                strip_prefix = sdk.strip_prefix,
                install_components = sdk.install_components,
            )

_sdk_tag = tag_class(
    attrs = {
        "name": attr.string(default = "hos_sdk"),
        "version": attr.string(default = _HOS_SDK_VERSION),
        "tag": attr.string(default = _HOS_SDK_TAG),
        "url": attr.string(),
        "sha256": attr.string(),
        "strip_prefix": attr.string(default = "command-line-tools"),
        "install_components": attr.string_list(default = []),
    },
)

hos_sdk = module_extension(
    implementation = _hos_sdk_extension_impl,
    tag_classes = {"sdk": _sdk_tag},
)
