package ncnn

import _ "embed"

// Embedded ncnn model files. Generated by:
//
//	bazel build //devops/tools/pnnx:models
//
// Made available via Bazel embedsrcs in BUILD.bazel.

//go:embed speaker_eres2net.ncnn.param
var speakerERes2NetParam []byte

//go:embed speaker_eres2net.ncnn.bin
var speakerERes2NetBin []byte

//go:embed vad_silero.ncnn.param
var vadSileroParam []byte

//go:embed vad_silero.ncnn.bin
var vadSileroBin []byte

//go:embed denoise_dtln1.ncnn.param
var denoiseDTLN1Param []byte

//go:embed denoise_dtln1.ncnn.bin
var denoiseDTLN1Bin []byte

//go:embed denoise_dtln2.ncnn.param
var denoiseDTLN2Param []byte

//go:embed denoise_dtln2.ncnn.bin
var denoiseDTLN2Bin []byte

func init() {
	RegisterModel(ModelSpeakerERes2Net, speakerERes2NetParam, speakerERes2NetBin)
	RegisterModel(ModelVADSilero, vadSileroParam, vadSileroBin)
	RegisterModel(ModelDenoiseDTLN1, denoiseDTLN1Param, denoiseDTLN1Bin)
	RegisterModel(ModelDenoiseDTLN2, denoiseDTLN2Param, denoiseDTLN2Bin)
}
